apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomodoro
  labels:
    app: pomodoro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pomodoro
  template:
    metadata:
      labels:
        app: pomodoro
    spec:
      containers:
      - name: pomodoro
        image: webserverdude/pomodoro-timer
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pomodoro
spec:
  selector:
    app: pomodoro
  ports:
    - port: 8000
      targetPort: 80
  type: ClusterIP
